### ISSUE TITLE
Hi kennethreitz, I want to create a Chinese version

### ISSUE THREAD

**Issue by CarGod** [kennethreitz/wsl-guide#4]
What should I do？

**Comment by glasslion** [comment]
I created a Chinese fork a few days ago, here is the  repo https://github.com/glasslion/wsl-guide-cn and the rtd link: http://wsl-guide-cn.readthedocs.io/.

Welcome to contribute.

**Comment by kennethreitz** [comment]
I'll link to this in the sidebar soon!

**Comment by kennethreitz** [comment]
linked on homepage! thanks so much!

**Comment by kennethreitz** [comment]
✨🍰✨
